title: "The Tomiak Chemnitzer Site"
description: "Built with Minimal Mistakes and GitHub Pages"
theme: null
remote_theme: mmistakes/minimal-mistakes@4.24.0
url: "https://tomiakchemnitzer.com"

author:
  name: "Josh Tomiak"
  avatar: assets/images/headshot.jpg
  bio: >-
    Josh studies music, computer science, and religion at UVA (class of 2026).
    When his grandparents showed him the Chemnitzer concertina that his great-grandather Walter Maczka played, 
    he was intrigued and set out to learn more about its story (and how to play it, a little!)
    This site became his medium to share the story of the concertina and its unique sound.

plugins:
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-archives

markdown: kramdown

navigation: main
include:
  - _pages

footer:
  links:  # leave empty or define only the links you want
      - label: "GitHub"
        icon: "fab fa-fw fa-github"
        url: "https://github.com/jTomiak-28/tomiak-chemnitzer.github.io"

atom_feed:
  hide: true

collections:
  manuscripts:
    output: true
    permalink: /manuscript-archive/:slug/

  articles:
    output: true
    permalink: /articles/:slug/

defaults:
  # _manuscripts
  - scope:
      path: ""
      type: manuscripts
    values:
      layout: single
      author_profile: true
